#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear

#IZIN SCRIPT
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear

# // Get Bot
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | head -n1 | cut -d ' ' -f 2)
CHATIDS=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"

# Getting notif transaksi user
CHATID2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 2)
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear

# Valid Script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/rifg67/script-rifts//main/ipx"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
    echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
    echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
    echo -e "             \033[0;33mContact Admin :\033[0m"
    echo -e "      \033[2;32mWhatsApp\033[0m wa.me/6283151636921"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    sleep 10
    reboot
  fi
}
checking_sc
clear
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)

# . Liner 
function baris_panjang() {
  echo -e "\033[5;36m ────────────────────────────────────── \033[0m"
}

function Xwan_Banner() {
clear
baris_panjang
echo -e "\033[95;1m     $nama       \033[0m"
baris_panjang
}

function Sc_Credit(){
sleep 1
baris_panjang
echo -e "\033[2;35m Terimakasih Telah Menggunakan \033[0m"
echo -e "\033[2;35m      Script Credit \033[0m"
echo -e "\033[2;35m        $nama  \033[0m"
baris_panjang
exit 1
}

loading() {
  local pid=$1
  local delay=0.1
  local spin='-\|/'
  while ps -p $pid > /dev/null; do
    local temp=${spin#?}
    printf "[%c] " "$spin"
    local spin=$temp${spin%"$temp"}
    sleep $delay
    printf "\b\b\b\b\b\b"
  done
  printf "    \b\b\b\b"
}

until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  Xwan_Banner
  baris_panjang
  echo -e " \033[37mJust input a number for-\033[0m"
  echo -e " \033[32mQuota Limit\033[0m"
  echo -e " \033[32mLimit IP\033[0m"
  echo -e " \033[37mFormat GB\033[0m"
  echo ""
  echo -e " \033[33m0\033[0m \033[37mfor Unlimited\033[0m"
  echo -e " \033[33m0\033[0m \033[37Mfor No Limit\033[0m"
  echo ""
  baris_panjang
  echo ""
  read -rp " Username         : " -e user
  if grep -i -w -q "$user" /etc/xray/config.json; then
    clear
    Xwan_Banner
    baris_panjang
    echo ""
    echo -e "\033[91m Name Salah: Username sudah terdaftar, silakan gunakan nama lain. \033[0m"
    echo ""
    baris_panjang
    Sc_Credit
  else
    CLIENT_EXISTS=0
    break
  fi
done

# === Custom UUID Section ===
echo ""
read -p " Custom UUID (kosongkan untuk random): " input_uuid
if [[ -z $input_uuid ]]; then
    uuid=$(cat /proc/sys/kernel/random/uuid)
else
    uuid=$input_uuid
fi

echo
read -p " Limit User (GB)  : " Quota
echo
read -p " Limit User (IP)  : " iplimit
echo
read -p " Expired (days)   : " masaaktif

sleep 3 & loading $!

tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=`date -d "$masaaktif days" +"%Y-%m-%d"`

# Tambahkan user ke config.json
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

systemctl restart xray

# Link Trojan Akun
trojanlink="trojan://${uuid}@${domain}:443?path=%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#${user}"
trojanlink1="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#${user}"
trojanlink2="trojan://${uuid}@${domain}:80?path=%2Ftrojan-ws&security=none&host=${domain}&type=ws#${user}"

cat >/var/www/html/trojan-$user.txt <<-END
======================
# Format Trojan GO/WS
- name: Trojan-$user-GO/WS
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}

# Format Trojan gRPC
- name: Trojan-$user-gRPC
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

FORMAT LINK
======================
Link Akun Trojan 
======================
Link WS          : 
${trojanlink}
======================
Link GRPC        : 
${trojanlink1}
======================
Days in  : $masaaktif Day
Expired  : $expe
END

# Buat folder data quota/iplimit
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi
if [[ $iplimit -gt 0 ]]; then
  mkdir -p /etc/kyt/limit/trojan/ip
  echo -e "$iplimit" > /etc/kyt/limit/trojan/ip/$user
fi
if [ -z ${Quota} ]; then
  Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/trojan/.trojan.db

# === Notif ke Admin ===

TEXT="<b>-----------------------------------------</b>
<b>           XRAY / TROJAN</b>
<b>-----------------------------------------</b>
<code>Remarks   : ${user}
Domain    : ${domain}
Quota     : ${Quota} GB
Limit IP  : ${iplimit} Devices
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
Network   : ws / grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : trojan-grpc</code>
<b>-----------------------------------------</b>
<b>Link WS</b>
<b>-----------------------------------------</b>
<code>${trojanlink}</code>
<b>-----------------------------------------</b>
<b>Link gRPC</b>
<b>-----------------------------------------</b>
<code>${trojanlink1}</code>
<b>-----------------------------------------</b>
<b>Format OpenClash :</b> https://${domain}:81/trojan-${user}.txt
<b>-----------------------------------------</b>
<b>Aktif Selama   :</b> ${masaaktif} Hari
<b>Dibuat Pada    :</b> ${tnggl}
<b>Berakhir Pada  :</b> ${expe}
<b>-----------------------------------------</b>"

# Kirim ke semua chatid admin
for CHATID in $CHATIDS; do
    curl -s --max-time "$TIME" -X POST "$URL" \
        -d "chat_id=${CHATID}" \
        -d "disable_web_page_preview=1" \
        -d "parse_mode=html" \
        --data-urlencode "text=${TEXT}" >/dev/null
done

# === Notif ke User ===
TEXT="<b>-----------------------------------------</b>
<b>TRANSAKSI BERHASIL</b>
<b>-----------------------------------------</b>
<b>» Produk : Trojan</b>
<b>» ISP :</b> ${ISP}
<b>» Domain :</b> ${domain}
<b>» Region :</b> ${CITY}
<b>» User :</b> ${user}
<b>» Aktif :</b> ${masaaktif} Hari
<b>» Limit IP :</b> ${iplimit} Devices
<b>» Dibuat   :</b> ${tnggl}
<b>» Berakhir :</b> ${expe}
<b>-----------------------------------------</b>
<i>Automatic Notification From Server...</i>"
curl -s --max-time $TIME -X POST "$URL2" \
     -d "chat_id=$CHATID2" \
     -d "disable_web_page_preview=1" \
     -d "parse_mode=html" \
     --data-urlencode "text=$TEXT" \
     --data-urlencode 'reply_markup={"inline_keyboard":[[{"text":"📦 ORDER","url":"https://t.me/frel01"},{"text":"💬 TESTIMONI","url":"https://whatsapp.com/channel/0029Vafk1D38F2pLQYx5Vu2B"}]]}' >/dev/null

# === Output ke Terminal ===
function Details_Account() {
echo -e "\033[37m TROJAN  \033[0m"
echo -e ""
echo -e "\033[37m Remarks      : ${user} \033[0m" 
echo -e "\033[37m Host/IP      : ${domain} \033[0m"
echo -e "\033[37m User Quota   : ${Quota} GB \033[0m"
echo -e "\033[37m User Ip      : ${iplimit} IP \033[0m"
echo -e "\033[37m Port TLS     : 443-900 \033[0m" 
echo -e "\033[37m Port WS      : 80,8080,8081-9999 \033[0m"
echo -e "\033[37m Key          : ${uuid} \033[0m"
echo -e "\033[37m ISP          : $ISP \033[0m"
echo -e "\033[37m Path         : /trojan-ws \033[0m" 
echo -e "\033[37m ServiceName  : trojan-grpc \033[0m"
baris_panjang
}
function Link_Json() {
echo -e "\033[37m Link TLS     : ${trojanlink} \033[0m" 
baris_panjang
echo -e "\033[37m Link NTLS    : ${trojanlink2} \033[0m" 
baris_panjang 
echo -e "\033[37m Link GRPC    : ${trojanlink1} \033[0m" 
baris_panjang
echo -e "\033[37m OpenClash    : https://${domain}:81/trojan-$user.txt \033[0m" 
}
function Details_Expiry() {
baris_panjang
echo -e " \033[33mDibuat      : $tnggl \033[0m "
echo -e " \033[33mExpired     : $expe \033[0m "
}
Xwan_Banner
Details_Account
Link_Json
Details_Expiry
Sc_Credit
