#!/bin/bash

# Fungsi untuk membersihkan layar
clear_screen() {
    clear
}

# Fungsi untuk mencetak teks berwarna merah
red() {
    echo -e "\\033[32;1m${*}\\033[0m"
}

# Fungsi untuk membuat garis panjang
baris_panjang() {
    echo -e "\033[5;36m ────────────────────────────────────── \033[0m"
}

# Fungsi untuk menampilkan banner
Xwan_Banner() {
    clear_screen
    baris_panjang
    echo -e "\033[95;1m     $nama       \033[0m"
    baris_panjang
}

# Fungsi untuk menampilkan kredit script
Sc_Credit() {
    sleep 1
    baris_panjang
    echo -e "\033[2;35m Terimakasih Telah Menggunakan \033[0m"
    echo -e "\033[2;35m      Script Credit \033[0m"
    echo -e "\033[2;35m        $nama  \033[0m"
    baris_panjang
    systemctl restart xray > /dev/null 2>&1
    service cron restart > /dev/null 2>&1
    exit 1
}

# Fungsi untuk menampilkan banner XRAY VMESS
BANNER() {
    clear_screen
    baris_panjang
    echo -e "\033[95;1m     XRAY VMESS    \033[0m"
    baris_panjang
}

# Fungsi untuk menampilkan loading
loading() {
    local pid=$1
    local delay=0.1
    local spin='-\|/'

    while ps -p "$pid" > /dev/null; do
        local temp=${spin#?}
        printf "[%c] " "$spin"
        local spin=$temp${spin%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done

    printf "    \b\b\b\b"
}

# Membersihkan layar
clear_screen

# Mendapatkan IP server
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear_screen

# // Get Bot
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | head -n1 | cut -d ' ' -f 2)
CHATIDS=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear_screen

# Mendapatkan konfigurasi bot trx
CHATID2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear_screen

# Validasi script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/rifg67/script-rifts//main/ipx"

checking_sc() {
    useexp=$(wget -qO- "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    if [[ $date_list < $useexp ]]; then
        echo -ne
    else
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
        echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
        echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
        echo -e "             \033[0;33mContact Admin :\033[0m"
        echo -e "      \033[2;32mWhatsApp\033[0m https://wa.me/6283151636921"
        echo -e "      \033[2;32mTelegram\033[0m https://t.me/frel01"
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        sleep 10
        reboot
    fi
}

checking_sc
clear_screen

# Mendapatkan informasi server
export TIME="10"
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear_screen

# Input username
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
    Xwan_Banner
    baris_panjang
    BANNER
    echo -e " \033[37mJust input a number for-\033[0m"
    echo -e " \033[32mQuota Limit\033[0m"
    echo -e " \033[32mLimit IP\033[0m"
    echo -e " \033[37mFormat GB\033[0m"
    echo ""
    echo -e " \033[33m0\033[0m \033[37mfor Unlimited\033[0m"
    echo -e " \033[33m0\033[0m \033[37mfor No Limit\033[0m"
    echo ""
    baris_panjang
    echo ""
    read -rp " Username         : " -e user

    if grep -i -w -q "$user" /etc/xray/config.json; then
        clear_screen
        Xwan_Banner
        baris_panjang
        echo ""
        echo -e "\033[91m Name Salah: Username sudah terdaftar, silakan gunakan nama lain. \033[0m"
        echo ""
        baris_panjang
        Sc_Credit
    else
        CLIENT_EXISTS=0
        break
    fi
done

# Input UUID
echo ""
read -p " Custom UUID (Enter untuk random) : " uuid_input
if [[ -z $uuid_input ]]; then
    uuid=$(cat /proc/sys/kernel/random/uuid)
else
    uuid=$uuid_input
fi

# Input quota, limit IP, dan masa aktif
echo
read -p " Limit User (GB)  : " Quota
echo
read -p " Limit User (IP)  : " iplimit
echo
read -p " Expired (days)   : " masaaktif
echo

# Simulasi loading
sleep 3 & 
loading $!

# Hitung tanggal
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")

# Tambahkan user ke config.json
sed -i '/#vmess$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vmessgrpc$/a\### '"$user $exp"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json

# Buat konfigurasi VMESS
vmess_json1=$(cat << EOF
{
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF
)

vmess_json2=$(cat << EOF
{
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF
)

vmess_json3=$(cat << EOF
{
      "v": "2",
      "ps": "${user}",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF
)

vmesslink1="vmess://$(echo "$vmess_json1" | base64 -w 0)"
vmesslink2="vmess://$(echo "$vmess_json2" | base64 -w 0)"
vmesslink3="vmess://$(echo "$vmess_json3" | base64 -w 0)"

# Buat file konfigurasi
cat >/var/www/html/vmess-$user.txt <<-END

======================
$nama
======================
# Format Vmess WS TLS

- name: Vmess-$user-WS TLS
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess WS Non TLS

- name: Vmess-$user-WS Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}

# Format Vmess gRPC

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

======================
 Link Akun Vmess
======================
Link TLS         : 
${vmesslink1}
======================
Link none TLS    : 
${vmesslink2}
======================
Link GRPC        : 
${vmesslink3}
======================
Aktif Selama   : $masaaktif Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $expe
======================

END

# Buat direktori jika belum ada
if [ ! -e /etc/vmess ]; then
    mkdir -p /etc/vmess
fi

# Set limit IP
if [[ $iplimit -gt 0 ]]; then
    mkdir -p /etc/kyt/limit/vmess/ip
    echo -e "$iplimit" > /etc/kyt/limit/vmess/ip/$user
fi

# Set quota
if [ -z "${Quota}" ]; then
    Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
    echo "${d}" >/etc/vmess/${user}
fi

# Update database
DATADB=$(cat /etc/vmess/.vmess.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
    sed -i "/\b${user}\b/d" /etc/vmess/.vmess.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vmess/.vmess.db

clear_screen

# Kirim notifikasi ke admin
TEXT="<b>------------------------------</b>
<b>      XRAY/VMESS</b>
<b>------------------------------</b>
<code>Remarks   : ${user}
Domain    : ${domain}
Quota     : ${Quota} GB
Limit IP  : ${iplimit} Devices
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vmess-grpc</code>
<b>------------------------------</b>
<b> VMESS WS TLS</b>
<b>------------------------------</b>
<code>${vmesslink1}</code>
<b>------------------------------</b>
<b>VMESS WS NO TLS</b>
<b>------------------------------</b>
<code>${vmesslink2}</code>
<b>------------------------------</b>
<b> VMESS gRPC</b>
<b>------------------------------</b>
<code>${vmesslink3}</code>
<b>------------------------------</b>
<b>Format OpenClash :</b> https://${domain}:81/vmess-$user.txt
<b>------------------------------</b>
<b>Aktif Selama   :</b> $masaaktif Hari
<b>Dibuat Pada    :</b> $tnggl
<b>Berakhir Pada  :</b> $expe
<b>------------------------------</b>
"

# Kirim ke semua chatid admin
for CHATID in $CHATIDS; do
    curl -s --max-time "$TIME" -X POST "$URL" \
        -d "chat_id=${CHATID}" \
        -d "disable_web_page_preview=1" \
        -d "parse_mode=html" \
        --data-urlencode "text=${TEXT}" >/dev/null
done

# Kirim notifikasi ke user
TEXT2="
<b>-----------------------------------------</b>
   <b>TRANSAKSI BERHASIL</b>
<b>-----------------------------------------</b>
<b>» Produk : VMess</b>
<b>» ISP :</b> ${ISP}
<b>» Domain :</b> ${domain}
<b>» Region :</b> ${CITY}
<b>» User :</b> ${user}
<b>» Aktif :</b> ${masaaktif} Hari
<b>» Limit IP :</b> ${iplimit} Devices
<b>» Dibuat   :</b> ${tnggl}
<b>» Berakhir :</b> ${expe}
<b>-----------------------------------------</b>
<i>Automatic Notification From Server...</i>
"

curl -s --max-time $TIME -X POST "$URL2" \
     -d "chat_id=$CHATID2" \
     -d "disable_web_page_preview=1" \
     -d "parse_mode=html" \
     --data-urlencode "text=$TEXT2" \
     --data-urlencode 'reply_markup={"inline_keyboard":[[{"text":"📦 ORDER","url":"https://t.me/frel01"},{"text":"💬 TESTIMONI","url":"https://whatsapp.com/channel/0029Vafk1D38F2pLQYx5Vu2B"}]]}' >/dev/null

# Fungsi untuk menampilkan detail akun
function Details_Account() {
    echo -e "\033[37m"
    baris_panjang
    echo -e " VMESS XRAY "
    baris_panjang
    echo -e ""
    echo -e " Remarks       : ${user}"
    echo -e " Domain        : ${domain}"
    echo -e " User Quota    : ${Quota} GB"
    echo -e " User Ip       : ${iplimit} IP"
    echo -e " Port TLS      : 400,8443"
    echo -e " port WS       : 80,8880,8080,2082"
    echo -e " Key           : ${uuid}"
    echo -e " Localtions    : $CITY"
    echo -e " ISP           : $ISP"
    echo -e " AlterId       : 0"
    echo -e " Security      : auto"
    echo -e " Network       : ws"
    echo -e " Path          : /vmess"
    echo -e " Dynamic Path  : yourbug/vmess"
    echo -e " ServiceName   : vmess-grpc"
    echo -e "\033[0m"
}

# Fungsi untuk menampilkan link
function Link_Json() {
    baris_panjang
    echo -e " Link TLS      : ${vmesslink1}"
    baris_panjang
    echo -e " Link WS       : ${vmesslink2}"
    baris_panjang
    echo -e " Link GRPC     : ${vmesslink3}"
    baris_panjang
    echo -e " OpenClash     : https://${domain}:81/vmess-$user.txt"
    baris_panjang
}

# Fungsi untuk menampilkan masa aktif
function Details_Expiry() {
    baris_panjang
    echo -e " \033[33mDibuat      : $tnggl \033[0m "
    echo -e " \033[33mExpired     : $expe \033[0m "
    baris_panjang
}

# Tampilkan hasil
Xwan_Banner
Details_Account
Link_Json
Details_Expiry
Sc_Credit