#!/bin/bash

# Fungsi untuk membersihkan layar
clear_screen() {
    clear
}

# Fungsi untuk mencetak teks berwarna merah
red() {
    echo -e "\\033[32;1m${*}\\033[0m"
}

# Fungsi untuk membuat garis panjang
baris_panjang() {
    echo -e "\033[5;36m ────────────────────────────────────── \033[0m"
}

# Fungsi untuk menampilkan banner
Xwan_Banner() {
    clear_screen
    baris_panjang
    echo -e "\033[95;1m     $nama       \033[0m"
    baris_panjang
}

# Fungsi untuk menampilkan banner XRAY VLESS
BANNER() {
    clear_screen
    baris_panjang
    echo -e "\033[95;1m     XRAY VLESS    \033[0m"
    baris_panjang
}

# Fungsi untuk menampilkan kredit script
Sc_Credit() {
    sleep 1
    baris_panjang
    echo -e "\033[2;35m Terimakasih Telah Menggunakan \033[0m"
    echo -e "\033[2;35m      Script Credit \033[0m"
    echo -e "\033[2;35m        $nama  \033[0m"
    baris_panjang
    systemctl restart xray > /dev/null 2>&1
    service cron restart > /dev/null 2>&1
    exit 1
}

# Fungsi untuk menampilkan loading
loading() {
    local pid=$1
    local delay=0.1
    local spin='-\|/'

    while ps -p "$pid" > /dev/null; do
        local temp=${spin#?}
        printf "[%c] " "$spin"
        local spin=$temp${spin%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done

    printf "    \b\b\b\b"
}

# Membersihkan layar
clear_screen

# Mendapatkan IP server
MYIP=$(curl -sS ipv4.icanhazip.com)
echo -e "\e[32mloading...\e[0m"
clear_screen

# // Get Bot
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | head -n1 | cut -d ' ' -f 2)
CHATIDS=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear_screen

# Mendapatkan konfigurasi bot trx
CHATID2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear_screen

# Validasi script
ipsaya=$(curl -sS ipv4.icanhazip.com)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/rifg67/script-rifts//main/ipx"

checking_sc() {
    useexp=$(wget -qO- "$data_ip" | grep "$ipsaya" | awk '{print $3}')
    if [[ $date_list < $useexp ]]; then
        echo -ne
    else
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        echo -e ""
        echo -e "            \033[91;1mPERMISSION DENIED !\033[0m"
        echo -e "   \033[0;33mYour VPS\033[0m $ipsaya \033[0;33mHas been Banned\033[0m"
        echo -e "     \033[0;33mBuy access permissions for scripts\033[0m"
        echo -e "             \033[0;33mContact Admin :\033[0m"
        echo -e "      \033[2;32mWhatsApp\033[0m wa.me/6283151636921"
        echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
        sleep 10
        reboot
    fi
}

checking_sc
clear_screen

# Mendapatkan informasi server
IP=$(curl -sS ipv4.icanhazip.com)
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear_screen

# Input username
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
    Xwan_Banner
    baris_panjang
    BANNER
    echo -e " \033[37mJust input a number for-\033[0m"
    echo -e " \033[32mQuota Limit\033[0m"
    echo -e " \033[32mLimit IP\033[0m"
    echo -e " \033[37mFormat GB\033[0m"
    echo ""
    echo -e " \033[33m0\033[0m \033[37mfor Unlimited\033[0m"
    echo -e " \033[33m0\033[0m \033[37mfor No Limit\033[0m"
    echo ""
    baris_panjang
    echo ""
    read -rp " Username         : " -e user

    if grep -i -w -q "$user" /etc/xray/config.json; then
        clear_screen
        Xwan_Banner
        baris_panjang
        echo ""
        echo -e "\033[91m Name Salah: Username sudah terdaftar, silakan gunakan nama lain. \033[0m"
        echo ""
        baris_panjang
        Sc_Credit
    else
        CLIENT_EXISTS=0
        break
    fi
done

# Input UUID
echo ""
read -p " Custom UUID (kosongkan untuk random): " input_uuid
if [[ -z $input_uuid ]]; then
    uuid=$(cat /proc/sys/kernel/random/uuid)
else
    uuid=$input_uuid
fi

# Input quota, limit IP, dan masa aktif
echo
read -p " Limit User (GB)  : " Quota
echo
read -p " Limit User (IP)  : " iplimit
echo
read -p " Expired (days)   : " masaaktif

# Simulasi loading
sleep 3 & 
loading $!

# Hitung tanggal
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
exp=$(date -d "$masaaktif days" +"%Y-%m-%d")

# Tambahkan user ke config.json
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json

# Buat link
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}"

# Buat direktori jika belum ada
if [ ! -e /etc/vless ]; then
    mkdir -p /etc/vless
fi

# Set limit IP
if [[ $iplimit -gt 0 ]]; then
    mkdir -p /etc/kyt/limit/vless/ip
    echo -e "$iplimit" > /etc/kyt/limit/vless/ip/$user
fi

# Set quota
if [ -z "${Quota}" ]; then
    Quota="0"
fi

c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
    echo "${d}" >/etc/vless/${user}
fi

# Update database
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
    sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid} ${Quota} ${iplimit}" >>/etc/vless/.vless.db

# Buat file konfigurasi
cat >/var/www/html/vless-$user.txt <<-END

======================
$nama 
======================
# Format Vless WS TLS

- name: Vless-$user-WS TLS
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}

# Format Vless WS Non TLS

- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true

# Format Vless gRPC (SNI)

- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
    grpc-mode: gun
    grpc-service-name: vless-grpc

======================
Link Akun Vless 
======================
Link TLS      : 
${vlesslink1}
======================
Link none TLS : 
${vlesslink2}
======================
Link GRPC     : 
${vlesslink3}
======================
Expired  : $masaaktif Day

END

# Kirim notifikasi
TEXT="<b>------------------------------</b>
<b>      XRAY/VLESS</b>
<b>------------------------------</b>
<code>Remarks   : ${user}
Domain    : ${domain}
Quota     : ${Quota} GB
Limit IP  : ${iplimit} Devices
Port TLS  : 400-900
Port NTLS : 80, 8080, 8081-9999
id        : ${uuid}
alterId   : 0
Security  : auto
network   : ws or grpc
Path      : /Multi-Path
Dynamic   : https://bugmu.com/path
Name      : vless-grpc</code>
<b>------------------------------</b>
<b>Link TLS</b>
<b>------------------------------</b>
<code>${vlesslink1}</code>
<b>------------------------------</b>
<b>Link none TLS</b>
<b>------------------------------</b>
<code>${vlesslink2}</code>
<b>------------------------------</b>
<b>Link GRPC</b>
<b>------------------------------</b>
<code>${vlesslink3}</code>
<b>------------------------------</b>
<b>Format OpenClash :</b> https://${domain}:81/vless-$user.txt
<code>------------------------------</code>
<b>Aktif Selama   :</b> $masaaktif Hari
<b>Dibuat Pada    :</b> $tnggl
<b>Berakhir Pada  :</b> $expe
<code>------------------------------</code>
"
# Kirim ke semua chatid admin
for CHATID in $CHATIDS; do
    curl -s --max-time "$TIME" -X POST "$URL" \
        -d "chat_id=${CHATID}" \
        -d "disable_web_page_preview=1" \
        -d "parse_mode=html" \
        --data-urlencode "text=${TEXT}" >/dev/null
done

# Notifikasi ke user
TEXT2="
<b>-----------------------------------------</b>
   <b>TRANSAKSI BERHASIL</b>
<b>-----------------------------------------</b>
<b>» Produk : VLess</b>
<b>» ISP :</b> ${ISP}
<b>» Domain :</b> ${domain}
<b>» Region :</b> ${CITY}
<b>» User :</b> ${user}
<b>» Aktif :</b> ${masaaktif} Hari
<b>» Limit IP :</b> ${iplimit} Devices
<b>» Dibuat   :</b> ${tnggl}
<b>» Berakhir :</b> ${expe}
<b>-----------------------------------------</b>
<i>Automatic Notification From Server...</i>
"

curl -s --max-time $TIME -X POST "$URL2" \
     -d "chat_id=$CHATID2" \
     -d "disable_web_page_preview=1" \
     -d "parse_mode=html" \
     --data-urlencode "text=$TEXT2" \
     --data-urlencode 'reply_markup={"inline_keyboard":[[{"text":"📦 ORDER","url":"https://t.me/frel01"},{"text":"💬 TESTIMONI","url":"https://whatsapp.com/channel/0029Vafk1D38F2pLQYx5Vu2B"}]]}' >/dev/null

# Tampilkan hasil
Xwan_Banner

function Details_Account() {
    echo -e "\033[37m VLESS XRAY \033[0m"
    baris_panjang
    echo -e "\033[37m Remarks     : ${user} "
    echo -e "\033[37m Domain      : ${domain}"
    echo -e "\033[37m User Quota  : ${Quota} GB"
    echo -e "\033[37m User Ip     : ${iplimit} IP"
    echo -e "\033[37m port TLS    : 443-900"
    echo -e "\033[37m port WS     : 80,8880,8080"
    echo -e "\033[37m User ID     : ${uuid}"
    echo -e "\033[37m Locations.  : $CITY"
    echo -e "\033[37m ISP         : $ISP"
    echo -e "\033[37m Encryption  : none"
    echo -e "\033[37m Path TLS    : /vless "
    echo -e "\033[37m ServiceName : vless-grpc"
}

function Link_Json() {
    baris_panjang
    echo -e "\033[37m Link TLS    : ${vlesslink1}"
    baris_panjang
    echo -e "\033[37m Link NTLS   : ${vlesslink2}"
    baris_panjang
    echo -e "\033[37m Link GRPC   : ${vlesslink3}"
    baris_panjang
    echo -e "\033[37m OpenClash   : https://${domain}:81/vless-$user.txt"
}

function Details_Expiry() {
    baris_panjang
    echo -e "\033[33m Days in    : $masaaktif Day \033[0m "
    echo -e "\033[33m Expiry     : $expe \033[0m "
}

Details_Account
Link_Json
Details_Expiry
Sc_Credit