#!/bin/bash

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
BG_BLU="\033[44;1m" # BG BIRU
GREN="\033[92m"
clear
# . 1
function Create_Account() {
  add-tro
}
# . 2
function Create_Trial() {
  trial-tro
}
# . 3
function Delete_Account() {
  del-tro
}
# . 4
function List_Member() {
  member-tro
}
# . 5
function Renew_Account() {
  renew-tro
}
# . 6
function Changes_Limit() {
  ganti-ip-trojan
}

# . 11
function Changes_Limit_Quota() {
  trojan-qouta
}
# . 7 
function Check_Account() {
  cek-tro
}
# . 8 
function Check_Details_Account() {
  check-tro
}

# . 9
function Lock_Account() {
  lock-tr
}

# . 10
function Unlock_Account() {
  unlock-tr
}

# . 11
function Recovery_Trojan() {
  recover-tr
}

# Menu
function Menu_Features() {
  echo -e "\033[97;1m┌────────────────────────────────────────────┐\033[0m"
  echo -e "\033[97;1m \033[0m \033[1;33m            TROJAN MANAGER MENU            \033[0m"
  echo -e "\033[97;1m├────────────────────────────────────────────┘\033[0m"
  echo -e "\033[97;1m│ \033[33m[01]\033[0m Create Account            \033[0m"
  echo -e "\033[97;1m│ \033[33m[02]\033[0m Trial Account             \033[0m"
  echo -e "\033[97;1m│ \033[33m[03]\033[0m Delete Account            \033[0m"
  echo -e "\033[97;1m│ \033[33m[04]\033[0m List Member Account       \033[0m"
  echo -e "\033[97;1m│ \033[33m[05]\033[0m Renew Account             \033[0m"
  echo -e "\033[97;1m│ \033[33m[06]\033[0m Change IP Accounts        \033[0m"
  echo -e "\033[97;1m│ \033[33m[07]\033[0m Change Limit Accounts     \033[0m"
  echo -e "\033[97;1m│ \033[33m[08]\033[0m Cek Account               \033[0m"
  echo -e "\033[97;1m│ \033[33m[09]\033[0m Cek Detail Account        \033[0m"
  echo -e "\033[97;1m│ \033[33m[10]\033[0m Lock Account              \033[0m"
  echo -e "\033[97;1m│ \033[33m[11]\033[0m Unlock Account            \033[0m"
  echo -e "\033[97;1m│ \033[33m[12]\033[0m Recovery Account          \033[0m"
  echo -e "\033[97;1m│ \033[33m[13]\033[0m Back to Main Menu         \033[0m"
  echo -e "\033[97;1m│ \033[92m[x]\033[0m  Exit                      \033[0m"
  echo -e "\033[97;1m└────────────────────────────────────────────┘\033[0m"
  echo -e ""
}

Menu_Features
read -p "Select From Options [1-14 or x] :  " Ltt
case $Ltt in
1) clear ; Create_Account ;;
2) clear ; Create_Trial ;;
3) clear ; Delete_Account ;;
4) clear ; List_Member ;;
5) clear ; Renew_Account ;;
6) clear ; Changes_Limit ;;
7) clear ; Changes_Limit_Quota ;;
8) clear ; Check_Account ;;
9) clear ; Check_Details_Account ;;
10) clear ; Lock_Account ;;
11) clear ; Unlock_Account ;;
12) clear ; Recovery_Trojan ;;
13) clear ; menu ;;
*) m-tro ;;
x) exit ;;
esac
