#!/bin/bash

# WARNA
BlueCyan='\e[5;36m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
Xark='\e[0m'
r="\033[1;91m"
ungu='\033[0;35m'
yellow='\e[33m'
BG_BLU="\033[44;1m"
GREN="\033[92m"

clear

# FUNGSI MENU XRAY VMESS
Create_Account()               { add-vme; }
Create_Trial()                 { trial-vme; }
Delete_Account()               { del-vme; }
List_Member()                  { member-vme; }
Renew_Account()                { renew-vme; }
Check_Account()                { cek-vme; }
Changes_Limit_Quota()          { change-vmess-qouta; }
Change_Ip_Vmess()              { ganti-ip-vmess; }
Changes_Limit_Xray()           { change-limit-xray; }
Detail_Config_Vmess()          { check-vme; }
Lock_Account_Vmess()           { lock-vm; }
Unlock_Account_Vmess()         { unlock-vm; }
Recovery_Vmess()               { recover-vm; }

Menu_Features() {
  echo -e "\033[97;1m┌────────────────────────────────────────────┐\033[0m"
  echo -e "\033[97;1m \033[0m \033[1;33m            VMESS MANAGER MENU            \033[0m"
  echo -e "\033[97;1m├────────────────────────────────────────────┘\033[0m"
  echo -e "\033[97;1m│ \033[33m[01]\033[0m Create Account            \033[0m"
  echo -e "\033[97;1m│ \033[33m[02]\033[0m Trial Account             \033[0m"
  echo -e "\033[97;1m│ \033[33m[03]\033[0m Delete Account            \033[0m"
  echo -e "\033[97;1m│ \033[33m[04]\033[0m List Member Account       \033[0m"
  echo -e "\033[97;1m│ \033[33m[05]\033[0m Renew Account             \033[0m"
  echo -e "\033[97;1m│ \033[33m[06]\033[0m Change IP limit Accounts   \033[0m"
  echo -e "\033[97;1m│ \033[33m[07]\033[0m Change Limit Bandwith Accounts \033[0m"
  echo -e "\033[97;1m│ \033[33m[08]\033[0m Cek Login Account               \033[0m"
  echo -e "\033[97;1m│ \033[33m[09]\033[0m Cek Detail Account        \033[0m"
  echo -e "\033[97;1m│ \033[33m[10]\033[0m Lock Account              \033[0m"
  echo -e "\033[97;1m│ \033[33m[11]\033[0m Unlock Account            \033[0m"
  echo -e "\033[97;1m│ \033[33m[12]\033[0m Recovery Account          \033[0m"
  echo -e "\033[97;1m│ \033[33m[13]\033[0m Back to Main Menu         \033[0m"
  echo -e "\033[97;1m│ \033[92m[x]\033[0m  Exit                      \033[0m"
  echo -e "\033[97;1m└────────────────────────────────────────────┘\033[0m"
  echo -e ""
}

Menu_Features

# INPUT PILIHAN
read -p "Select From Options [1-24 or x]: " Ltt

case $Ltt in
  1)  clear; Create_Account ;;
  2)  clear; Create_Trial ;;
  3)  clear; Delete_Account ;;
  4)  clear; List_Member ;; 
  5)  clear; Renew_Account ;;
  6)  clear; Change_Ip_Vmess ;;
  7)  clear; Changes_Limit_Quota ;;
  8)  clear; Check_Account ;;
  9)  clear; Detail_Config_Vmess ;;
  10) clear; Lock_Account_Vmess ;;
  11) clear; Unlock_Account_Vmess ;;
  12) clear; Recovery_Vmess ;;
  13) clear; menu ;;
  x|X) exit ;;
  *)  clear; m-vme ;;
esac
