#!/bin/bash
name="PEYX"

cd /etc/systemd/system/
rm -rf kyt.service
cd
grenbo="\e[92;1m"
NC='\e[0m'

cd /usr/bin
rm -rf regip
rm -rf regip.zip
sudo apt update
sudo apt install pip
apt install unzip
apt install neofetch -y
cd /usr/bin
clear
pip install requests python-telegram-bot==13.7
clear
cd

figlet "PEYX" | lolcat
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m          ADD BOT PANEL          \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
read -e -p "Masukkan ID Telegram :" admin
echo -e ''$admin'' >> /usr/local/sbin/regip/xwan.txt
clear

cat > /etc/systemd/system/kyt.service << END
[Unit]
Description=Simple kyt - @kyt
After=network.target

[Service]
WorkingDirectory=/usr/local/sbin/regip
ExecStart=/usr/bin/python3  regis.py
Restart=always

[Install]
WantedBy=multi-user.target
END

systemctl start kyt 
systemctl enable kyt
systemctl restart kyt
cd /root
rm -rf bot.sh
rm -rf bot.sh.1
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "🍀VPS SUCCESSFULLY INSTALL BOT🍀"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "🌹NAME AUTHOR : $name"
echo -e "🌺ADMIN BOT   : $admin"
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
clear

echo " Installations selesai, kode /start untuk menjalankan bot"
