#!/bin/bash
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"

ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
nama=$(cat /etc/xray/username)
clear
# // Get Bot
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | head -n1 | cut -d ' ' -f 2)
CHATIDS=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
# getting Bot Produk
CHATID2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 3)
KEY2=$(grep -E "^#bottrx# " "/etc/bottrx/.bottrx.db" | cut -d ' ' -f 2)
export TIME="10"
export URL2="https://api.telegram.org/bot$KEY2/sendMessage"
clear
IP=$(curl -sS ipv4.icanhazip.com)
Login=Trial-`</dev/urandom tr -dc X-Z0-9 | head -c4`
hari="1"
Pass=order
iplimit=1
#limitip
if [[ $iplimit -gt 0 ]]; then
mkdir -p /etc/kyt/limit/ssh/ip/
echo -e "$iplimit" > /etc/kyt/limit/ssh/ip/$Login
else
echo > /dev/null
fi
clear
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
clear
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e `date -d "$masaaktif days" +"%Y-%m-%d"` -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
hariini=`date -d "0 days" +"%Y-%m-%d"`
expi=`date -d "$masaaktif days" +"%Y-%m-%d"`
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null

function baris_panjang(){
echo -e "${BlueCyan} ◇━━━━━━━━━━━━━━━━━◇ ${Xark} "
}

function Xwan_Banner() {
clear
baris_panjang
echo -e "\033[95;1m     $nama       \033[0m"
baris_panjang
}


clear
Xwan_Banner
echo -e "\033[35;0m     SET MINUTES    \033[0m"
baris_panjang
echo
echo
read -p " Minutes : " pup
echo userdel ${Login} | at now + $pup minutes &> /dev/null

# Isi pesan notif
TEXT="
<code>------------------------------</code>
<code>SSH OVPN Account     </code>
<code>------------------------------</code>
<code>Username         : </code> <code>$Login</code>
<code>Password         : </code> <code>$Pass</code>
<code>Limit Quota      : </code> <code>$Quota</code>
<code>Limit IP         : </code> <code>$iplimit</code>
<code>------------------------------</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080, 8081-9999 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 400-900</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>------------------------------</code>
<code>SSH WEBSOCKET    : </code><code>$domain:80@$Login:$Pass</code>
<code>SSH SSL          : </code><code>$domain:443@$Login:$Pass</code>
<code>SSH UDP          : </code><code>$domain:1-65535@$Login:$Pass</code>
<code>------------------------------</code>
<code>Payload WSS      : </code><code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>------------------------------</code>
OVPN Download : https://$domain:81/
<code>------------------------------</code>
<code>Save Link Account: </code>https://$domain:81/ssh-$Login.txt
<code>------------------------------</code>
Aktif Selama         : $pup Menit
<code>------------------------------</code>
"
# Kirim ke semua chatid
for CHATID in $CHATIDS; do
    curl -s --max-time "$TIME" \
        -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" \
        "$URL" >/dev/null
done

CHATID="$CHATID2"
KEY2="$KEY2"
TIME="$TIME"
URL="$URL2"
TEXT="
<b>-----------------------------------------</b>
   <b>TRANSAKSI SUKSES</b>
<b>-----------------------------------------</b>
<b>» Produk : Trial SSH</b>
<b>» ISP :</b> ${ISP}
<b>» Region :</b> ${CITY}
<b>» User :</b> ${Login}
<b>» Aktif :</B> $pup Menit
<b>» Limit IP :</b> ${iplimit} Devices
<b>-----------------------------------------</b>
<i>Automatic Notification From Server...</i>
"'&reply_markup={"inline_keyboard":[[{"text":"📦 ORDER ","url":"https://t.me/frel01"},{"text":"💬 TESTIMONI ","url":"https://whatsapp.com/channel/0029Vafk1D38F2pLQYx5Vu2B"}]]}'
curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
clear
echo ""
mkdir -p /etc/ssh

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/ssh/${Login}
fi
echo ""
cat > /var/www/html/ssh-$Login.txt <<-END
======================
Format SSH OVPN Account
======================
Username         : $Login
Password         : $Pass
Berakhir Pada  : $pup Menit
======================
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port Dropbear    : 443, 109
Port SSH UDP     : 1-65535
Port SSH WS      : 80, 8080, 8081-9999
Port SSH SSL WS  : 443
Port SSL/TLS     : 400-900
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
======================
Payload : GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]
======================
OVPN Download : https://$domain:81/
======================

END
PAYLOADWS="GET / HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADTLS="GET wss://$domain/ HTTP/1.1[crlf]Host: [host][crlf]Connection: Upgrade[crlf]User-Agent: [ua][crlf]Upgrade: websocket[crlf][crlf]"

PAYLOADHANCED="HEAD / HTTP/1.1[crlf]Host: Masukan_Bug[crlf][crlf]PATCH / HTTP/1.1[crlf]Host: [host][crlf]Upgrade: websocket[crlf][crlf][split]HTTP/ 1[crlf][crlf] "

BlueCyan='\e[5;36m'
Xark='\e[0m'
ungu='\033[0;35m'
yellow='\e[33m'
WhiteBe='\e[5;37m'
GreenBe='\e[5;32m'
BlueCyan='\e[5;36m'
Xark='\e[0m'
clear
function baris_panjang(){
echo -e "${BlueCyan} ◇━━━━━━━━━━━━━━━━━◇ ${Xark} "
}
# Sc Credit
function Sc_Credit(){
baris_panjang
echo -e "${ungu}  Terimakasih Telah Menggunakan Script-"
echo -e "       Credit    $nama"
echo -e "${Xark}"
baris_panjang
exit 1
}

# Port Account Detail
function Ssh_Details(){
echo -e "${WhiteBe}"
baris_panjang
echo " SSH OPENVPN "
echo ""
echo " Remark   : ${Login}"
echo " pasword  : ${Pass}"
echo " limit ip : ${iplimit}"
echo " Domain   : ${domain}"
echo " Port Udp : 1-65535 "
echo " Port WS  : 80,8880,2082,8080"
echo " Port Tls : 443,8443 "
echo " OpenSSH  : 22,143 "
echo " OVPN Tls : 443 "
echo " Ovpn UdP : 2200 "
echo " Ovpn Tcp : 443 "
baris_panjang
}

# Payload Detail 
function Payload_Details(){
baris_panjang
echo -e "${WhiteBe}"
echo " Payload WS    : ${PAYLOADWS}"
baris_panjang
echo " Payload Tls   : ${PAYLOADTLS}"
baris_panjang
echo " Payload Hnced : ${PAYLOADHANCED}"
echo -e "${Xark}"
baris_panjang
}

# Expired Account
function Expiry_Account(){
echo -e "${yellow} Expiry in  : ${pup} "
baris_panjang
}
Ssh_Details
Payload_Details
Expiry_Account
Sc_Credit